"""Restricted Python acceptance commands for packaged Windows builds.

RockCore is itself packaged with Python, but that interpreter is not exposed as
``python.exe``.  This module provides deterministic validation for the small
subset of Python commands generated by planners and workers, so a valid task is
not failed merely because the target PC has no system Python on PATH.
"""

from __future__ import annotations

import io
import multiprocessing
import os
import re
import shlex
import subprocess
import sys
import threading
import tokenize
import unittest
from pathlib import Path, PureWindowsPath


PYTHON_COMMANDS = {"python", "python3", "py"}
_SHELL_OPERATORS = {"&&", "||", ";", "|", ">", ">>", "<"}
_UNITTEST_LOCK = threading.RLock()


def _split_command(command: str) -> list[str]:
    looks_windows = bool(re.match(r'^\s*["\']?[A-Za-z]:\\', command or ""))
    try:
        values = shlex.split(
            command, posix=not (sys.platform == "win32" or looks_windows)
        )
    except ValueError:
        return []
    return [value.strip('"\'') for value in values]


def _executable_name(value: str) -> str:
    path = PureWindowsPath(value) if "\\" in value else Path(value)
    name = path.name.lower()
    for suffix in (".exe", ".cmd", ".bat", ".com"):
        if name.endswith(suffix):
            name = name[:-len(suffix)]
            break
    return name


def _python_arguments(command: str) -> list[str] | None:
    values = _split_command(command)
    if not values or _executable_name(values[0]) not in PYTHON_COMMANDS:
        return None
    if any(value in _SHELL_OPERATORS for value in values[1:]):
        return None
    arguments = values[1:]
    if _executable_name(values[0]) == "py" and arguments:
        if re.fullmatch(r"-\d+(?:\.\d+)?(?:-\d+)?", arguments[0]):
            arguments = arguments[1:]
    return arguments


def _project_path(root: Path, value: str) -> Path:
    candidate = Path(value)
    if not candidate.is_absolute():
        candidate = root / candidate
    resolved = candidate.resolve()
    try:
        resolved.relative_to(root)
    except ValueError as error:
        raise ValueError(f"验收文件超出项目目录：{value}") from error
    return resolved


def _compile_source(path: Path) -> str:
    if not path.is_file():
        return f"文件不存在：{path}"
    try:
        with tokenize.open(path) as source_file:
            source = source_file.read()
        compile(source, str(path), "exec")
    except (OSError, UnicodeError, SyntaxError) as error:
        return f"{path.name}: {error}"
    return ""


def _run_py_compile(arguments: list[str], root: Path) -> subprocess.CompletedProcess:
    files = [value for value in arguments if not value.startswith("-")]
    if not files:
        return subprocess.CompletedProcess(
            ["embedded-python", "-m", "py_compile"], 2, "",
            "py_compile 未指定文件",
        )
    errors = []
    checked = []
    for value in files:
        try:
            path = _project_path(root, value)
        except ValueError as error:
            errors.append(str(error))
            continue
        checked.append(path.relative_to(root).as_posix())
        issue = _compile_source(path)
        if issue:
            errors.append(issue)
    if errors:
        return subprocess.CompletedProcess(
            ["embedded-python", "-m", "py_compile", *files], 1, "",
            "\n".join(errors),
        )
    return subprocess.CompletedProcess(
        ["embedded-python", "-m", "py_compile", *files], 0,
        "RockCore 内置 Python 语法验收通过：" + ", ".join(checked) + "\n",
        "",
    )


def _run_compileall(arguments: list[str], root: Path) -> subprocess.CompletedProcess:
    values = [value for value in arguments if not value.startswith("-")] or ["."]
    files: list[Path] = []
    errors = []
    for value in values:
        try:
            target = _project_path(root, value)
        except ValueError as error:
            errors.append(str(error))
            continue
        if target.is_dir():
            files.extend(sorted(target.rglob("*.py")))
        elif target.suffix.lower() == ".py":
            files.append(target)
        else:
            errors.append(f"找不到 Python 文件或目录：{value}")
    checked = []
    for path in dict.fromkeys(files):
        checked.append(path.relative_to(root).as_posix())
        issue = _compile_source(path)
        if issue:
            errors.append(issue)
    if errors:
        return subprocess.CompletedProcess(
            ["embedded-python", "-m", "compileall", *values], 1, "",
            "\n".join(errors),
        )
    return subprocess.CompletedProcess(
        ["embedded-python", "-m", "compileall", *values], 0,
        f"RockCore 内置 Python 语法验收通过：{len(checked)} 个文件\n", "",
    )


def _run_unittest(arguments: list[str], root: Path) -> subprocess.CompletedProcess:
    stream = io.StringIO()
    _UNITTEST_LOCK.acquire()
    before_modules = set(sys.modules)
    previous_cwd = Path.cwd()
    previous_path = list(sys.path)
    try:
        os.chdir(root)
        sys.path.insert(0, str(root))
        verbosity = 2 if "-v" in arguments or "--verbose" in arguments else 1
        runner = unittest.TextTestRunner(stream=stream, verbosity=verbosity)
        program = unittest.main(
            module=None,
            argv=["embedded-python", *arguments],
            testRunner=runner,
            exit=False,
        )
        result = program.result
    except SystemExit as error:
        return subprocess.CompletedProcess(
            ["embedded-python", "-m", "unittest", *arguments],
            int(error.code or 2), stream.getvalue(), str(error),
        )
    except BaseException as error:  # unittest must report import/runtime failures
        return subprocess.CompletedProcess(
            ["embedded-python", "-m", "unittest", *arguments],
            1, stream.getvalue(), f"unittest 启动失败：{error}",
        )
    finally:
        os.chdir(previous_cwd)
        sys.path[:] = previous_path
        # Avoid leaking dynamically imported user modules into later projects.
        for name in set(sys.modules) - before_modules:
            module = sys.modules.get(name)
            module_file = getattr(module, "__file__", "") if module else ""
            if not module_file:
                continue
            try:
                Path(module_file).resolve().relative_to(root)
            except (OSError, ValueError):
                continue
            sys.modules.pop(name, None)
        _UNITTEST_LOCK.release()

    output = stream.getvalue()
    if result is None:
        return subprocess.CompletedProcess(
            ["embedded-python", "-m", "unittest", *arguments],
            1, output, "unittest 未返回执行结果",
        )
    return subprocess.CompletedProcess(
        ["embedded-python", "-m", "unittest", *arguments],
        0 if result.wasSuccessful() else 1,
        "RockCore 内置 Python unittest 验收\n" + output,
        "",
    )


def _unittest_worker(connection, arguments: list[str], root_text: str):
    """Run user tests in a disposable child so timeout cleanup is reliable."""
    try:
        result = _run_unittest(arguments, Path(root_text))
        connection.send((result.returncode, result.stdout, result.stderr))
    except BaseException as error:
        connection.send((1, "", f"unittest 子进程失败：{error}"))
    finally:
        connection.close()


def _run_unittest_isolated(
    arguments: list[str], root: Path, timeout: int | float
) -> subprocess.CompletedProcess:
    context = multiprocessing.get_context("spawn")
    parent, child = context.Pipe(duplex=False)
    process = context.Process(
        target=_unittest_worker,
        args=(child, arguments, str(root)),
        name="RockCorePythonValidation",
    )
    process.start()
    child.close()
    try:
        if parent.poll(max(1.0, float(timeout))):
            returncode, stdout, stderr = parent.recv()
            process.join(timeout=2)
            if process.is_alive():
                process.terminate()
                process.join(timeout=2)
            return subprocess.CompletedProcess(
                ["embedded-python", "-m", "unittest", *arguments],
                int(returncode), str(stdout or ""), str(stderr or ""),
            )
        process.terminate()
        process.join(timeout=2)
        return subprocess.CompletedProcess(
            ["embedded-python", "-m", "unittest", *arguments],
            124, "", f"RockCore 内置 unittest 超时（{timeout:g} 秒）",
        )
    except (EOFError, OSError) as error:
        process.join(timeout=2)
        return subprocess.CompletedProcess(
            ["embedded-python", "-m", "unittest", *arguments],
            1, "", f"无法读取 unittest 子进程结果：{error}",
        )
    finally:
        parent.close()


def run_embedded_python_command(
    command: str, project_root: str | os.PathLike[str], *,
    timeout: int | float = 120,
) -> subprocess.CompletedProcess | None:
    """Run a supported Python validation command, otherwise return ``None``."""
    arguments = _python_arguments(command)
    if arguments is None:
        return None
    while arguments and arguments[0] in {"-B", "-E", "-I", "-s", "-S"}:
        arguments = arguments[1:]
    if len(arguments) < 2 or arguments[0] != "-m":
        return None
    module = arguments[1].lower()
    module_arguments = arguments[2:]
    root = Path(project_root).resolve()
    if module == "py_compile":
        return _run_py_compile(module_arguments, root)
    if module == "compileall":
        return _run_compileall(module_arguments, root)
    if module == "unittest":
        return _run_unittest_isolated(module_arguments, root, timeout)
    return None
