"""Restricted Python acceptance commands for packaged Windows builds.

RockCore is itself packaged with Python, but that interpreter is not exposed as
``python.exe``.  This module provides deterministic validation for the small
subset of Python commands generated by planners and workers, so a valid task is
not failed merely because the target PC has no system Python on PATH.
"""

from __future__ import annotations

import io
import contextlib
import multiprocessing
import os
import re
import runpy
import shlex
import subprocess
import sys
import threading
import time
import tokenize
import traceback
import unittest
from pathlib import Path, PureWindowsPath

from app.subprocess_utils import terminate_process_tree


PYTHON_COMMANDS = {"python", "python3", "py"}
_SHELL_OPERATORS = {"&&", "||", ";", "|", ">", ">>", "<"}
_UNITTEST_LOCK = threading.RLock()
_PYTEST_RUNTIME_ARGS = (
    "-p", "no:cacheprovider",
    # A windowed PyInstaller executable has no real stderr file descriptor.
    # Pytest's faulthandler plugin unconditionally asks stderr for fileno(),
    # which raises io.UnsupportedOperation in that environment. RockCore
    # already captures tracebacks and writes its own diagnostic log.
    "-p", "no:faulthandler",
)


def _split_command(command: str) -> list[str]:
    looks_windows = bool(re.match(r'^\s*["\']?[A-Za-z]:\\', command or ""))
    try:
        values = shlex.split(
            command, posix=not (sys.platform == "win32" or looks_windows)
        )
    except ValueError:
        return []
    return [value.strip('"\'') for value in values]


def _executable_name(value: str) -> str:
    path = PureWindowsPath(value) if "\\" in value else Path(value)
    name = path.name.lower()
    for suffix in (".exe", ".cmd", ".bat", ".com"):
        if name.endswith(suffix):
            name = name[:-len(suffix)]
            break
    return name


def _python_arguments(command: str) -> list[str] | None:
    values = _split_command(command)
    if not values:
        return None
    executable = _executable_name(values[0])
    if executable not in PYTHON_COMMANDS and not re.fullmatch(
        r"python\d+(?:\.\d+)*", executable
    ):
        return None
    if any(value in _SHELL_OPERATORS for value in values[1:]):
        return None
    arguments = values[1:]
    if _executable_name(values[0]) == "py" and arguments:
        if re.fullmatch(r"-\d+(?:\.\d+)?(?:-\d+)?", arguments[0]):
            arguments = arguments[1:]
    return arguments


def _pytest_arguments(command: str) -> list[str] | None:
    values = _split_command(command)
    if not values or _executable_name(values[0]) != "pytest":
        return None
    if any(value in _SHELL_OPERATORS for value in values[1:]):
        return None
    return values[1:]


def _project_path(root: Path, value: str) -> Path:
    candidate = Path(value)
    if not candidate.is_absolute():
        candidate = root / candidate
    resolved = candidate.resolve()
    try:
        resolved.relative_to(root)
    except ValueError as error:
        raise ValueError(f"验收文件超出项目目录：{value}") from error
    return resolved


def _compile_source(path: Path) -> str:
    if not path.is_file():
        return f"文件不存在：{path}"
    try:
        with tokenize.open(path) as source_file:
            source = source_file.read()
        compile(source, str(path), "exec")
    except (OSError, UnicodeError, SyntaxError) as error:
        return f"{path.name}: {error}"
    return ""


def _run_py_compile(arguments: list[str], root: Path) -> subprocess.CompletedProcess:
    files = [value for value in arguments if not value.startswith("-")]
    if not files:
        return subprocess.CompletedProcess(
            ["embedded-python", "-m", "py_compile"], 2, "",
            "py_compile 未指定文件",
        )
    errors = []
    checked = []
    for value in files:
        try:
            path = _project_path(root, value)
        except ValueError as error:
            errors.append(str(error))
            continue
        checked.append(path.relative_to(root).as_posix())
        issue = _compile_source(path)
        if issue:
            errors.append(issue)
    if errors:
        return subprocess.CompletedProcess(
            ["embedded-python", "-m", "py_compile", *files], 1, "",
            "\n".join(errors),
        )
    return subprocess.CompletedProcess(
        ["embedded-python", "-m", "py_compile", *files], 0,
        "RockCore 内置 Python 语法验收通过：" + ", ".join(checked) + "\n",
        "",
    )


def _run_compileall(arguments: list[str], root: Path) -> subprocess.CompletedProcess:
    values = [value for value in arguments if not value.startswith("-")] or ["."]
    files: list[Path] = []
    errors = []
    for value in values:
        try:
            target = _project_path(root, value)
        except ValueError as error:
            errors.append(str(error))
            continue
        if target.is_dir():
            files.extend(sorted(target.rglob("*.py")))
        elif target.suffix.lower() == ".py":
            files.append(target)
        else:
            errors.append(f"找不到 Python 文件或目录：{value}")
    checked = []
    for path in dict.fromkeys(files):
        checked.append(path.relative_to(root).as_posix())
        issue = _compile_source(path)
        if issue:
            errors.append(issue)
    if errors:
        return subprocess.CompletedProcess(
            ["embedded-python", "-m", "compileall", *values], 1, "",
            "\n".join(errors),
        )
    return subprocess.CompletedProcess(
        ["embedded-python", "-m", "compileall", *values], 0,
        f"RockCore 内置 Python 语法验收通过：{len(checked)} 个文件\n", "",
    )


def _run_unittest(arguments: list[str], root: Path) -> subprocess.CompletedProcess:
    stream = io.StringIO()
    _UNITTEST_LOCK.acquire()
    before_modules = set(sys.modules)
    previous_cwd = Path.cwd()
    previous_path = list(sys.path)
    previous_bytecode = sys.dont_write_bytecode
    try:
        os.chdir(root)
        sys.path.insert(0, str(root))
        sys.dont_write_bytecode = True
        verbosity = 2 if "-v" in arguments or "--verbose" in arguments else 1
        runner = unittest.TextTestRunner(stream=stream, verbosity=verbosity)
        program = unittest.main(
            module=None,
            argv=["embedded-python", *arguments],
            testRunner=runner,
            exit=False,
        )
        result = program.result
    except SystemExit as error:
        return subprocess.CompletedProcess(
            ["embedded-python", "-m", "unittest", *arguments],
            int(error.code or 2), stream.getvalue(), str(error),
        )
    except BaseException as error:  # unittest must report import/runtime failures
        return subprocess.CompletedProcess(
            ["embedded-python", "-m", "unittest", *arguments],
            1, stream.getvalue(), f"unittest 启动失败：{error}",
        )
    finally:
        os.chdir(previous_cwd)
        sys.path[:] = previous_path
        sys.dont_write_bytecode = previous_bytecode
        # Avoid leaking dynamically imported user modules into later projects.
        for name in set(sys.modules) - before_modules:
            module = sys.modules.get(name)
            module_file = getattr(module, "__file__", "") if module else ""
            if not module_file:
                continue
            try:
                Path(module_file).resolve().relative_to(root)
            except (OSError, ValueError):
                continue
            sys.modules.pop(name, None)
        _UNITTEST_LOCK.release()

    output = stream.getvalue()
    if result is None:
        return subprocess.CompletedProcess(
            ["embedded-python", "-m", "unittest", *arguments],
            1, output, "unittest 未返回执行结果",
        )
    return subprocess.CompletedProcess(
        ["embedded-python", "-m", "unittest", *arguments],
        0 if result.wasSuccessful() else 1,
        "RockCore 内置 Python unittest 验收\n" + output,
        "",
    )


def _unittest_worker(connection, arguments: list[str], root_text: str):
    """Run user tests in a disposable child so timeout cleanup is reliable."""
    try:
        result = _run_unittest(arguments, Path(root_text))
        connection.send((result.returncode, result.stdout, result.stderr))
    except BaseException as error:
        connection.send((1, "", f"unittest 子进程失败：{error}"))
    finally:
        connection.close()


def _wait_for_validation_result(
    parent, process, timeout: int | float,
    cancel_event: threading.Event | None = None,
) -> bool | None:
    """Poll an isolated validation child while allowing async cancellation."""
    deadline = time.monotonic() + max(1.0, float(timeout))
    while True:
        if cancel_event is not None and cancel_event.is_set():
            terminate_process_tree(process)
            process.join(timeout=2)
            return None
        remaining = deadline - time.monotonic()
        if remaining <= 0:
            return False
        if parent.poll(min(0.25, remaining)):
            return True


def _run_unittest_isolated(
    arguments: list[str], root: Path, timeout: int | float,
    cancel_event: threading.Event | None = None,
) -> subprocess.CompletedProcess:
    context = multiprocessing.get_context("spawn")
    parent, child = context.Pipe(duplex=False)
    process = context.Process(
        target=_unittest_worker,
        args=(child, arguments, str(root)),
        name="RockCorePythonValidation",
    )
    process.start()
    child.close()
    try:
        ready = _wait_for_validation_result(
            parent, process, timeout, cancel_event
        )
        if ready is None:
            return subprocess.CompletedProcess(
                ["embedded-python", "-m", "unittest", *arguments],
                130, "", "RockCore 内置 unittest 已取消",
            )
        if ready:
            returncode, stdout, stderr = parent.recv()
            process.join(timeout=2)
            if process.is_alive():
                terminate_process_tree(process)
                process.join(timeout=2)
            return subprocess.CompletedProcess(
                ["embedded-python", "-m", "unittest", *arguments],
                int(returncode), str(stdout or ""), str(stderr or ""),
            )
        terminate_process_tree(process)
        process.join(timeout=2)
        return subprocess.CompletedProcess(
            ["embedded-python", "-m", "unittest", *arguments],
            124, "", f"RockCore 内置 unittest 超时（{timeout:g} 秒）",
        )
    except (EOFError, OSError) as error:
        process.join(timeout=2)
        return subprocess.CompletedProcess(
            ["embedded-python", "-m", "unittest", *arguments],
            1, "", f"无法读取 unittest 子进程结果：{error}",
        )
    finally:
        parent.close()


def _run_pytest_in_process(
    arguments: list[str], root: Path
) -> subprocess.CompletedProcess:
    """Run pytest in the current process and restore all mutable state."""
    stdout = io.StringIO()
    stderr = io.StringIO()
    previous_cwd = Path.cwd()
    previous_path = list(sys.path)
    previous_bytecode = sys.dont_write_bytecode
    previous_qt = os.environ.get("QT_QPA_PLATFORM")
    previous_plugin_setting = os.environ.get("PYTEST_DISABLE_PLUGIN_AUTOLOAD")
    try:
        import pytest

        root = Path(root).resolve()
        os.chdir(root)
        sys.path.insert(0, str(root))
        sys.dont_write_bytecode = True
        # Desktop acceptance must also work on Windows machines without a
        # display session or third-party pytest plugins installed globally.
        os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")
        os.environ["PYTEST_DISABLE_PLUGIN_AUTOLOAD"] = "1"
        with contextlib.redirect_stdout(stdout), contextlib.redirect_stderr(stderr):
            returncode = int(pytest.main([*arguments, *_PYTEST_RUNTIME_ARGS]))
        return subprocess.CompletedProcess(
            ["embedded-python", "-m", "pytest", *arguments],
            returncode,
            stdout.getvalue(),
            stderr.getvalue(),
        )
    except BaseException as error:
        traceback_text = "".join(traceback.format_exception(error))
        return subprocess.CompletedProcess(
            ["embedded-python", "-m", "pytest", *arguments],
            1,
            stdout.getvalue(),
            stderr.getvalue()
            + f"RockCore 内置 pytest 启动失败：{error}\n{traceback_text}",
        )
    finally:
        os.chdir(previous_cwd)
        sys.path[:] = previous_path
        sys.dont_write_bytecode = previous_bytecode
        if previous_qt is None:
            os.environ.pop("QT_QPA_PLATFORM", None)
        else:
            os.environ["QT_QPA_PLATFORM"] = previous_qt
        if previous_plugin_setting is None:
            os.environ.pop("PYTEST_DISABLE_PLUGIN_AUTOLOAD", None)
        else:
            os.environ["PYTEST_DISABLE_PLUGIN_AUTOLOAD"] = previous_plugin_setting


def run_packaged_pytest_smoke_test(
    arguments: list[str], root: str | os.PathLike[str]
) -> subprocess.CompletedProcess:
    """Exercise bundled pytest without spawning another frozen executable.

    The caller already is a dedicated short-lived smoke-test process. Running
    pytest directly here avoids nesting PyInstaller multiprocessing during a
    Windows package build, while normal project validations remain isolated.
    """
    return _run_pytest_in_process(arguments, Path(root))


def _pytest_worker(connection, arguments: list[str], root_text: str):
    """Run pytest from RockCore's packaged runtime in a disposable process."""
    try:
        result = _run_pytest_in_process(arguments, Path(root_text))
        connection.send((result.returncode, result.stdout, result.stderr))
    except BaseException as error:
        connection.send((
            1, "", "RockCore 内置 pytest 子进程失败："
            + "".join(traceback.format_exception(error)),
        ))
    finally:
        connection.close()


def _run_pytest_isolated(
    arguments: list[str], root: Path, timeout: int | float,
    cancel_event: threading.Event | None = None,
) -> subprocess.CompletedProcess:
    context = multiprocessing.get_context("spawn")
    parent, child = context.Pipe(duplex=False)
    process = context.Process(
        target=_pytest_worker,
        args=(child, arguments, str(root)),
        name="RockCorePytestValidation",
    )
    process.start()
    child.close()
    command = ["embedded-python", "-m", "pytest", *arguments]
    try:
        ready = _wait_for_validation_result(
            parent, process, timeout, cancel_event
        )
        if ready is None:
            return subprocess.CompletedProcess(
                command, 130, "", "RockCore 内置 pytest 已取消",
            )
        if ready:
            returncode, stdout, stderr = parent.recv()
            process.join(timeout=2)
            if process.is_alive():
                terminate_process_tree(process)
                process.join(timeout=2)
            prefix = "RockCore 内置 Python pytest 验收\n"
            return subprocess.CompletedProcess(
                command, int(returncode), prefix + str(stdout or ""),
                str(stderr or ""),
            )
        terminate_process_tree(process)
        process.join(timeout=2)
        return subprocess.CompletedProcess(
            command, 124, "", f"RockCore 内置 pytest 超时（{timeout:g} 秒）",
        )
    except (EOFError, OSError) as error:
        process.join(timeout=2)
        return subprocess.CompletedProcess(
            command, 1, "", f"无法读取 pytest 子进程结果：{error}",
        )
    finally:
        parent.close()


def _script_worker(connection, arguments: list[str], root_text: str):
    """Run a Python script or ``-c`` check without a host interpreter."""
    stdout = io.StringIO()
    stderr = io.StringIO()
    root = Path(root_text).resolve()
    previous_cwd = Path.cwd()
    previous_path = list(sys.path)
    previous_argv = list(sys.argv)
    returncode = 0
    try:
        os.chdir(root)
        sys.path.insert(0, str(root))
        with contextlib.redirect_stdout(stdout), contextlib.redirect_stderr(stderr):
            if arguments[:1] == ["-c"] and len(arguments) >= 2:
                sys.argv = ["-c", *arguments[2:]]
                namespace = {"__name__": "__main__", "__file__": "<string>"}
                exec(compile(arguments[1], "<string>", "exec"), namespace)
            elif arguments and not arguments[0].startswith("-"):
                script = _project_path(root, arguments[0])
                sys.argv = [str(script), *arguments[1:]]
                runpy.run_path(str(script), run_name="__main__")
            else:
                raise ValueError(
                    "RockCore 内置 Python 不支持该验收参数；"
                    "支持 pytest、unittest、py_compile、compileall、脚本和 -c"
                )
    except SystemExit as error:
        returncode = int(error.code) if isinstance(error.code, int) else 1
    except BaseException:
        returncode = 1
        with contextlib.redirect_stderr(stderr):
            traceback.print_exc()
    finally:
        os.chdir(previous_cwd)
        sys.path[:] = previous_path
        sys.argv[:] = previous_argv
    connection.send((returncode, stdout.getvalue(), stderr.getvalue()))
    connection.close()


def _run_script_isolated(
    arguments: list[str], root: Path, timeout: int | float,
    cancel_event: threading.Event | None = None,
) -> subprocess.CompletedProcess:
    context = multiprocessing.get_context("spawn")
    parent, child = context.Pipe(duplex=False)
    process = context.Process(
        target=_script_worker,
        args=(child, arguments, str(root)),
        name="RockCorePythonScriptValidation",
    )
    process.start()
    child.close()
    command = ["embedded-python", *arguments]
    try:
        ready = _wait_for_validation_result(
            parent, process, timeout, cancel_event
        )
        if ready is None:
            return subprocess.CompletedProcess(
                command, 130, "", "RockCore 内置 Python 验收已取消",
            )
        if ready:
            returncode, stdout, stderr = parent.recv()
            process.join(timeout=2)
            if process.is_alive():
                terminate_process_tree(process)
                process.join(timeout=2)
            return subprocess.CompletedProcess(
                command, int(returncode), str(stdout or ""), str(stderr or ""),
            )
        terminate_process_tree(process)
        process.join(timeout=2)
        return subprocess.CompletedProcess(
            command, 124, "", f"RockCore 内置 Python 脚本验收超时（{timeout:g} 秒）",
        )
    except (EOFError, OSError) as error:
        process.join(timeout=2)
        return subprocess.CompletedProcess(
            command, 1, "", f"无法读取 Python 验收子进程结果：{error}",
        )
    finally:
        parent.close()


def run_embedded_python_command(
    command: str, project_root: str | os.PathLike[str], *,
    timeout: int | float = 120,
    cancel_event: threading.Event | None = None,
) -> subprocess.CompletedProcess | None:
    """Run Python validation with RockCore, never with a host interpreter.

    ``None`` means the command is not Python-related. Every recognized Python
    or pytest command is handled here, including a clear failure for unsupported
    modules, so callers cannot accidentally fall back to ``python`` on PATH.
    """
    root = Path(project_root).resolve()
    values = _split_command(command)
    if values:
        executable = _executable_name(values[0])
        python_related = (
            executable in PYTHON_COMMANDS
            or executable == "pytest"
            or bool(re.fullmatch(r"python\d+(?:\.\d+)*", executable))
        )
        if python_related and any(
            value in _SHELL_OPERATORS for value in values[1:]
        ):
            return subprocess.CompletedProcess(
                ["embedded-python"], 2, "",
                "RockCore 内置 Python 验收不接受 shell 组合操作；"
                "请将每条验收命令分别执行。",
            )
    pytest_arguments = _pytest_arguments(command)
    if pytest_arguments is not None:
        return _run_pytest_isolated(
            pytest_arguments, root, timeout, cancel_event
        )

    arguments = _python_arguments(command)
    if arguments is None:
        return None
    while arguments and arguments[0] in {"-B", "-E", "-I", "-s", "-S", "-u"}:
        arguments = arguments[1:]
    if arguments[:1] in (["--version"], ["-V"]):
        return subprocess.CompletedProcess(
            ["embedded-python", *arguments], 0,
            f"Python {sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro} "
            "(RockCore 内置)\n", "",
        )
    if len(arguments) >= 2 and arguments[0] == "-m":
        module = arguments[1].lower()
        module_arguments = arguments[2:]
        if module == "py_compile":
            return _run_py_compile(module_arguments, root)
        if module == "compileall":
            return _run_compileall(module_arguments, root)
        if module == "unittest":
            return _run_unittest_isolated(
                module_arguments, root, timeout, cancel_event
            )
        if module == "pytest":
            return _run_pytest_isolated(
                module_arguments, root, timeout, cancel_event
            )
        return subprocess.CompletedProcess(
            ["embedded-python", *arguments], 2, "",
            f"RockCore 内置 Python 不支持验收模块：{module}。"
            "请使用 pytest、unittest、py_compile 或 compileall。",
        )
    return _run_script_isolated(arguments, root, timeout, cancel_event)
